version: '3'
services:
  #MongoDB
  mongodb:
    image: mongo
    volumes:
      - ./mongodb:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URI = ${MONGO_URI}
      - WEBSITE = ${WEBSITE}
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb: {}