version: '3'
services:
  #MongoDB
  mongodb:
    image: mongo
    volumes:
      - ./mongodb:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URI = $${{ secrets.MONGO_URI }}
      - WEBSITE = $${{ secrets.WEBSITE }}
    depends_on:
      - mongodb

volumes:
  mongodb: {}
